#++++++++++++++++++++++++++++++++++++++db++++++++++++
spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:32768/bpm-activiti?characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
  username: root
  password: root


#+++++++++++++++++++++++++++++++++++++++mybatis++++++
mybatis:
 mapperLocations: classpath:mybatis/*.xml



#+++++++++++++++++++++++++++++++++++++++base++++++
server:
 port: 8082



#+++++++++++++++++++++++++++++++++++++++log4j2++++++
logging:
 config: classpath:log4j2.properties